I'm making a few small changes to ACL2 (development copy) and a few centaur/ books, so that the centaur/ and taspi/ books certify in ACL2, not just ACL2(h), e.g., as follows:
(time nice make -j 8 regression-hons-fresh ACL2_HONS_OPT='-j8' ACL2=<path_to_acl2>) >& make-regression.log&

I think this will be nice, so that for example people using ACL2 (not
just ACL2(h)) can take advantage of the many Davis/Swords books
created under centaur/ that don't require ACL2(h) -- a recent one that
comes to mind is centaur/misc/tailrec.lisp.  Later I might streamline
the regression methodology.

Below is an outline of the changes to books/centaur/.

----------

In books/centaur/aig/bddify.lisp I added #+hons in front of the
progn! form that calls mht and profile-fn.

----------

In books/centaur/tutorial/counter.lisp I got this error when
certifying with ACL2 (as opposed to ACL2(h)):

   Error:  Undefined function SET-AND-RESET-GC-THRESHOLDS called with arguments () .

The problem was caused by evaluation of this form:

(value-triple (set-max-mem (* 3 (expt 2 30))))

My solution is to conditionalize in centaur/misc/memory-mgmt-raw.lisp
as follows:

#+hons
(include-raw "hons-analyze-memory-raw.lsp")

----------

I think it was to be expected that the following books took a lot of
time in ACL2, as opposed to ACL2(h) -- in fact I didn't even let them
finish:

books/centaur/tutorial/counter.lisp
books/centaur/tutorial/alu16-book.lisp

So I added some #+hons annotations to speed things up (admittedly by
eliminating what is mainly provided by these books).

----------


git-svn-id: http://acl2-books.googlecode.com/svn/trunk@1342 303c5b2c-9740-0410-b014-fd8f9db7be32